import type { Mbti } from '~/types/personalities.types'

export const MBTI_TYPES = ref<Mbti[]>([
  {
    name: 'The Protagonist (ENFJ-A)',
    code: 'enfj-a',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Protagonist (ENFJ-T)',
    code: 'enfj-t',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Campaigner (ENFP-A)',
    code: 'enfp-a',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Campaigner (ENFP-T)',
    code: 'enfp-t',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Commander (ENTJ-A)',
    code: 'entj-a',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Commander (ENTJ-T)',
    code: 'entj-t',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Debater (ENTP-A)',
    code: 'entp-a',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Debater (ENTP-T)',
    code: 'entp-t',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Entertainer (ESFP-A)',
    code: 'esfp-a',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Entertainer (ESFP-T)',
    code: 'esfp-t',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Consul (ESFJ-A)',
    code: 'esfj-a',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Consul (ESFJ-T)',
    code: 'esfj-t',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Executive (ESTJ-A)',
    code: 'estj-a',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Executive (ESTJ-T)',
    code: 'estj-t',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Entrepreneur (ESTP-A)',
    code: 'estp-a',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Entrepreneur (ESTP-T)',
    code: 'estp-t',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Advocate (INFJ-A)',
    code: 'infj-a',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Advocate (INFJ-T)',
    code: 'infj-t',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Mediator (INFP-A)',
    code: 'infp-a',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Mediator (INFP-T)',
    code: 'infp-t',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Architect (INTJ-A)',
    code: 'intj-a',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Architect (INTJ-T)',
    code: 'intj-t',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Logician (INTP-A)',
    code: 'intp-a',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Logician (INTP-T)',
    code: 'intp-t',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Defender (ISFJ-A)',
    code: 'isfj-a',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Defender (ISFJ-T)',
    code: 'isfj-t',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Adventurer (ISFP-A)',
    code: 'isfp-a',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Adventurer (ISFP-T)',
    code: 'isfp-t',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Logistician (ISTJ-A)',
    code: 'istj-a',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Logistician (ISTJ-T)',
    code: 'istj-t',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Virtuoso (ISTP-A)',
    code: 'istp-a',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Virtuoso (ISTP-T)',
    code: 'istp-t',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
])
