import type { Mbti } from '~/types/personalities.types'

export const MBTI_TYPES = ref<Mbti[]>([
  {
    name: 'The Protagonist (ENFJ-A)',
    code: 'enfja',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Protagonist (ENFJ-T)',
    code: 'enfjt',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Campaigner (ENFP-A)',
    code: 'enfpa',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Campaigner (ENFP-T)',
    code: 'enfpt',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Commander (ENTJ-A)',
    code: 'entja',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Commander (ENTJ-T)',
    code: 'entjt',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Debater (ENTP-A)',
    code: 'entpa',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Debater (ENTP-T)',
    code: 'entpt',
    energy: 'Extraversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Entertainer (ESFP-A)',
    code: 'esfpa',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Entertainer (ESFP-T)',
    code: 'esfpt',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Consul (ESFJ-A)',
    code: 'esfja',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Consul (ESFJ-T)',
    code: 'esfjt',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Executive (ESTJ-A)',
    code: 'estja',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Executive (ESTJ-T)',
    code: 'estjt',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Entrepreneur (ESTP-A)',
    code: 'estpa',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Entrepreneur (ESTP-T)',
    code: 'estpt',
    energy: 'Extraversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Advocate (INFJ-A)',
    code: 'infja',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Advocate (INFJ-T)',
    code: 'infjt',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Mediator (INFP-A)',
    code: 'infpa',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Mediator (INFP-T)',
    code: 'infpt',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Architect (INTJ-A)',
    code: 'intja',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Architect (INTJ-T)',
    code: 'intjt',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Logician (INTP-A)',
    code: 'intpa',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Logician (INTP-T)',
    code: 'intpt',
    energy: 'Introversion',
    perception: 'Intuition',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Defender (ISFJ-A)',
    code: 'isfja',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Defender (ISFJ-T)',
    code: 'isfjt',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Adventurer (ISFP-A)',
    code: 'isfpa',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Adventurer (ISFP-T)',
    code: 'isfpt',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Feeling',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
  {
    name: 'The Logistician (ISTJ-A)',
    code: 'istja',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Assertive',
  },
  {
    name: 'The Logistician (ISTJ-T)',
    code: 'istjt',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Judging',
    identity: 'Turbulent',
  },
  {
    name: 'The Virtuoso (ISTP-A)',
    code: 'istpa',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Assertive',
  },
  {
    name: 'The Virtuoso (ISTP-T)',
    code: 'istpt',
    energy: 'Introversion',
    perception: 'Sensing',
    decision: 'Thinking',
    structure: 'Perceiving',
    identity: 'Turbulent',
  },
])
