# netlify.toml
[build]
  command = "npm run generate"
  publish = ".output/public"

# This rule correctly handles 404 pages for a static site
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404